using System.Xml.Serialization;
using System.Xml.Linq;

namespace Reports
{
    public class XmlReport : ReportBase
    {
        public override string ToString()
        {
            return $"XML-report was successfully saved!";
        }

        public class ReportData
        {
            public List<Model.Point> FPoints { get; set; }
            public List<Model.Point> GPoints { get; set; }
            public double MaximumX { get; set; }
            public double MaximumValue { get; set; }
        }

        public override void GenerateReport(string filename, List<Model.Point> fPoints, List<Model.Point> gPoints, double maxX, double maxValue)
        {
                try
                {
                    var report = new ReportData
                    {
                        FPoints = fPoints,
                        GPoints = gPoints,
                        MaximumX = maxX,
                        MaximumValue = maxValue
                    };

                    var serializer = new XmlSerializer(typeof(ReportData));
                    XDocument doc;
                    using (var ms = new MemoryStream())
                    {
                        var ns = new XmlSerializerNamespaces();
                        ns.Add(string.Empty, string.Empty);
                        serializer.Serialize(ms, report, ns);
                        ms.Position = 0;
                        doc = XDocument.Load(ms);
                    }

                    doc.AddFirst(new XComment("Report generated by Coursework application."));

                    if (doc.Root != null)
                    {
                        doc.Root.AddFirst(new XComment("Contains maximum value and lists of points for functions F and G."));

                        var fEl = doc.Root.Element("FPoints");
                        if (fEl != null)
                            fEl.AddBeforeSelf(new XComment("FPoints: list of points for function F (each point has X and Y)."));

                        var gEl = doc.Root.Element("GPoints");
                        if (gEl != null)
                            gEl.AddBeforeSelf(new XComment("GPoints: list of points for function G (each point has X and Y)."));
                    }

                    doc.Save(filename);
                }
                catch (System.Exception ex)
                {
                    throw new System.Exception($"Error generating XML report: {ex.Message}");
                }
        }

    }
}
